app:
  appName: Clean Architecture - NodeJS - Organization by themes
  description: Demo of Clean Architecture in NodeJS using a organization of componentes by themes
  environment: dev
log:  
  level: debug # modes available orderer by magnitude: error, warning, info, debug
api:
  file: openapi.yaml
express:
  port: 8080
  enableCors: false
  serverTimeout: 10s
  httpsAlways: false
modules:
  - name: sequelize
    isAsync: false
  - name: expressOpenApiServer
    isAsync: true
database:
  sequelize:
    dbname: gamecollector-db
    dbuser: gamecollector-user
    dbpasswd: alfa1beta2
    dbhost: localhost
    dbdialect: mysql
    models:
      - sequelizeGamesystemModel
    