app:
  appName: Clean Architecture - NodeJS - Organization by themes
  description: Demo of Clean Architecture in NodeJS using a organization of componentes by themes
  environment: dev
log:  
  level: debug # modes available orderer by magnitude: error, warning, info, debug
express:
  enableCors: false
  timeout: 10s
  httpsAlways: false
database:
  dbname: gamecollector-db
  dbuser: gamecollector-user
  dbpasswd: alfa1beta2
  dbhost: localhost
  dbdialect: mysql
  # // TODO : implementar un metodo que obtenga todos los modelos automáticamente para evitar tener que declararlos aquí
  models:
    - sequelizeGamesystemModel
    