app:
  appName: Clean Architecture - NodeJS - Organization by themes
  description: Demo of Clean Architecture in NodeJS using a organization of componentes by themes
  environment: dev
log:  
  level: debug # modes available orderer by magnitude: error, warning, info, debug
  module: logWinston # modules available: consoleLogger, logColorLogger, logWinston
api:
  file: openapi.yaml
express:
  port: 8080
  enableCors: false
  serverTimeout: 10s
  httpsAlways: false
modules:
  - name: logging
    isAsync: false
  - name: expressOpenApiServer
    isAsync: true
  - name: sequelize
    isAsync: false
  - name: authentication
    isAsync: false
authentication:
  tokenExpiration: 30 #minutes
  tokenSecret: fromzerotohero
database:
  sequelize:
    dbname: gamecollector-db
    dbuser: gamecollector-user
    dbpasswd: alfa1beta2
    dbhost: localhost
    dbdialect: mysql
    models:
      - sequelizeGamesystemModel
  inconfig:
    users:
      - username: adminuser
        password: $2b$12$RBWhNB1fRhP8FWqR2z6YEeYUU7nae5wy7Zgw65ghXQar6pZ5lfrPm
        role: administrator
      - username: vieweruser
        password: $2b$12$RBWhNB1fRhP8FWqR2z6YEeYUU7nae5wy7Zgw65ghXQar6pZ5lfrPm
        role: viewer
    